### ISSUE TITLE
无法安装“ezshine.rainbow-fart-waifu”扩展，因为它与 VS Code 的当前版本(版本 1.47.0)不兼容。

### ISSUE THREAD

**Issue by abigmiu** [ezshine/vscode-rainbow-fart-waifu#4]
macos 10.14.6

vscode
版本: 1.47.0
提交: d5e9aa0227e057a60c82568bf31c04730dc15dcd
日期: 2020-07-09T08:01:54.115Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Comment by ezshine** [comment]
升级你的VSCode
