### ISSUE TITLE
vscode的插件没有声音

### ISSUE THREAD

**Issue by longlongchaoren** [ezshine/vscode-rainbow-fart-waifu#8]
我同时下载了Hbuilderx和vscode的插件并且另外安装了容器，Hbuilderx没问题，但是发现在vscode里输入关键字只会触发文字而没有声音，这样的情况该如何解决呢 ？

**Comment by ezshine** [comment]
看看vscode的插件路径里是否有空格，这个mp3播放的win32程序不能接受带空格的路径。
